### ISSUE TITLE
MTOUCH : warning MT1302: Could not extract the native library

### ISSUE THREAD

**Issue by x21Kenobi** [xamarin/GoogleApisForiOSComponents#169] opened 2018-08-07 12:52 UTC
Hey there,

I don't know if this is the correct place to write this,
but I found an anomaly with Firebase (iOS packages) and Xamarin.Build.Download (0.4.11).

### Similar Issues
The problem that I meet is similar to these issues:
* https://github.com/xamarin/GoogleApisForiOSComponents/issues/144
* https://github.com/xamarin/GoogleApisForiOSComponents/issues/158 

## The problem

If you try to build a project that using the following `packages.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.19.2" targetFramework="xamarinios10" />
  <package id="System.Net.Http" version="4.3.3" targetFramework="xamarinios10" />
  <package id="Xam.Plugin.DeviceInfo" version="3.1.0" targetFramework="xamarinios10" />
  <package id="Xam.Plugins.Settings" version="3.1.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Build.Download" version="0.4.11" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Analytics" version="4.0.5.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="4.0.13.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="2.0.8" targetFramework="xamarinios10" />
  <package id="Xamarin.Forms" version="2.5.0.280555" targetFramework="xamarinios10" />
</packages>
```
With this command line:
```bash
msbuild /t:Clean,Build,Archive /p:Configuration=Debug iOS/MyProj.iOS.csproj /v:diag
```
You should get an error like this:
```
"~/workspace/iOS/MyProj.iOS.csproj" (Clean;Build;Archive target) (1) ->
(_CompileToNative target) ->
  clang : error : no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseCore' [~/workspace/iOS/MyProj.iOS.csproj]
  clang : error : no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseAnalytics' [~/workspace/iOS/MyProj.iOS.csproj]
  clang : error : no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseCoreDiagnostics' [~/workspace/iOS/MyProj.iOS.csproj]
  clang : error : no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseNanoPB' [~/workspace/iOS/MyProj.iOS.csproj]
  clang : error : no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseInstanceID' [~/workspace/iOS/MyProj.iOS.csproj]
  error MT5209 : Native linking error : clang: error: no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseCore' [~/workspace/iOS/MyProj.iOS.csproj]
  error MT5209 : Native linking error : clang: error: no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseAnalytics' [~/workspace/iOS/MyProj.iOS.csproj]
  error MT5209 : Native linking error : clang: error: no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseCoreDiagnostics' [~/workspace/iOS/MyProj.iOS.csproj]
  error MT5209 : Native linking error : clang: error: no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseNanoPB' [~/workspace/iOS/MyProj.iOS.csproj]
  error MT5209 : Native linking error : clang: error: no such file or directory: '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseInstanceID' [~/workspace/iOS/MyProj.iOS.csproj]
  MTOUCH : error MT5202: Native linking failed. Please review the build log. [~/workspace/iOS/MyProj.iOS.csproj]
```
I did some debug and I found also these warnings messages:
```
Xamarin.iOS 11.12.0 using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk (TaskId:477)
MTOUCH : warning MT1302: Could not extract the native library 'FirebaseCore' from '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseCore'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary'). [~/workspace/iOS/MyProj.iOS.csproj]
MTOUCH : warning MT1302: Could not extract the native library 'FirebaseAnalytics' from '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseAnalytics'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary'). [~/workspace/iOS/MyProj.iOS.csproj]
MTOUCH : warning MT1302: Could not extract the native library 'FirebaseCoreDiagnostics' from '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseCoreDiagnostics'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary'). [~/workspace/iOS/MyProj.iOS.csproj]
MTOUCH : warning MT1302: Could not extract the native library 'FirebaseNanoPB' from '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseNanoPB'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary'). [~/workspace/iOS/MyProj.iOS.csproj]
MTOUCH : warning MT1302: Could not extract the native library 'FirebaseInstanceID' from '~/workspace/iOS/obj/iPhone/Debug/mtouch-cache/FirebaseInstanceID'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary'). [~/workspace/iOS/MyProj.iOS.csproj]
  Process exited with code 1, command: (TaskId:477)
```

## "Workaround"

Casually, when I was looking for a workaround, I read the dependencies needs to `Xamarin.Firebase.iOS.Analytics`

So, instead  `Xamarin.Build.Download.0.4.11`, I tried to using:
```xml
  <package id="Xamarin.Build.Download" version="0.4.6" targetFramework="xamarinios10" />
```
**And the build ends with no errors!**

## Considerations

1. I'm not sure whether this problem would be a dev or sys error, **but downgrading the version of 'Xamarin.Build.Download' worked for me**.

2. In your README.md seems there are no explicit references to specific dependencies and in [nuget](https://www.nuget.org/packages/Xamarin.Firebase.iOS.Analytics/) I see ` Xamarin.Build.Download (>= 0.4.6) `: **so I guess `Xamarin.Firebase.*` packages should work also with `0.4.11`. If not, I think you should declare this better!**

3. Based on the first 2 points, I don't know if that would be a workaround.

4. In any case, **the WARN messages should be elevated to ERROR messages, because it's impossible to finish the linking phase without those files.**

5. I don't want criticize your project management, but I was trying to do some debug, building my project directly with [your source code](https://github.com/xamarin/GoogleApisForiOSComponents), and I realized that is impossible go back to that specific version: there aren't tags for previous versions.

Regards,
Luke

**Comment by santoshg31** [comment] 2018-08-09 08:43
Hi I am getting exactly same error mentioned in issue 158.But none of the solutions worked for me.
However I am not using Xamarin Forms but I have created a project in  mvvmcross with .NetStandard 2.0 as my core.Connecting to mac having  Xcode 9 and have pushnotifications enabled in my provisioning profile.Also have enabled push notifications in Entitlements.plist.

One thing I noted in this solution is the  packageconfig does not include CloudMessaging package so is it not required ?
Is there something I need to do with linkerpleaseinclude file ?

I guess the setup would be the same for Firebase  irrespective if it is a XamarinForms ios project or an independent ios project but please correct me if I am wrong.

Will it be possible to share some sample code/project  as well please where firebase is implemented in ios.
Found at below two places though
http://blog.xamarians.com/Blog/2017/9/18/firebase-cloud-messaging
https://qiita.com/yamachu/items/cee6104ac579ea657deb

Thanks,
Santosh

**Comment by newky2k** [comment] 2018-08-20 21:24
@x21Kenobi @santoshg31  could you please provide a small samples with each of your issues so that we can investigate further.

Thanks in advance

**Comment by x21Kenobi** [comment] 2018-08-21 17:47
Hi @newky2k,
unfortunately, I can't.

The project is under internal policy rules of the company where I work and now we have resolve with that "workaround".
As I wrote previously, I didn't open this ticket to criticize your project but to leave a trace of the problem we had encountered.
Maybe this was only a case and nobody will encounter it (I hope).

Regards,
Luke

**Comment by x21Kenobi** [comment] 2018-08-21 17:49
Hi @newky2k,
unfortunately, I can't.

As I wrote previously, I didn't open this ticket to criticize your project but to leave a trace of the problem we had encountered.
Maybe this was only a case and nobody will encounter it (I hope).

Regards,
Luke

**Comment by santoshg31** [comment] 2018-08-22 09:49
Hi @newky2k, sorry even I won't be able to share.
However I have managed to build the solution in a very weird way.
1. First I upgraded the Cloudmessaging package from 2.0.8.1 to 3.0.3 which upgraded the other firebase packages as well. I was able to successfully build where Xamarin.Build.Download version was 0.4.6. However I got a message at the top saying unable uinstall the package 
 Xamarin.Build.Download 0.4.6 asking to me to restart visual studio.
2. So after restarting I discovered my Xamarin.Build.Download was upgraded to 0.4.11 and my build failed. So as @x21Kenobi   suggested I downgraded Xamarin.Build.Download to 0.4.6 but it aautomatically downgraded CloudMessaging package to 2.0.8.1 and also the subsequent firebase package and then my build was successfull. I have no clue what happened as this was the state i was before I upgraded cloudmessaging to 3.0.3. But atleast  I am now able to successfully build the solution with the below packages.

`  <package id="Xamarin.Build.Download" version="0.4.6" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Analytics" version="4.0.5.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.CloudMessaging" version="2.0.8.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="4.0.13.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="2.0.8" targetFramework="xamarinios10" />`

I am not using Xamarin.Forms but have created an application using MVVMCross with  android and ios as UIProjects. I have got the FirebaseBase notification working in android  but I am still searching for a proper setup code for ios as there is no proper documentation like in android for it. Only found the below two links but it seems like I not able to get the firebase token at all.
http://blog.xamarians.com/Blog/2017/9/18/firebase-cloud-messaging
https://qiita.com/yamachu/items/cee6104ac579ea657deb

`Firebase.InstanceID.InstanceId.Notifications.ObserveTokenRefresh((sender, e) =>
            {
                var newToken = Firebase.InstanceID.InstanceId.SharedInstance.Token;
                // if you want to send notification per user, use this token
                System.Diagnostics.Debug.WriteLine(newToken);

                //connectFCM();
            });`

The code never comes in this handler.
@x21Kenobi  @newky2k, can you please help what I might be missing here. Are there any samples that I can refer specifically for ios . I am relatively new to mobile development any help would be really appreciated !!

Thanks,
Santosh

**Comment by x21Kenobi** [comment] 2018-08-22 12:33
Hi @santoshg31

do you the code online on github?
I mean, is open source? If yes, where can I see it?

Regards,
Luke

**Comment by santoshg31** [comment] 2018-08-22 16:03
Hi @x21Kenobi  
Sorry I don't have the code on github but here is Appdelegate class which I created referring the above two links. Hope this helps in identifying whats going wrong.

`[Register("AppDelegate")]
    public class AppDelegate : MvxApplicationDelegate, IUNUserNotificationCenterDelegate
    {
        // class-level declarations

        public override UIWindow Window
        {
            get;
            set;
        }

        public CKDatabase PublicDatabase { get; set; }
        public CKDatabase PrivateDatabase { get; set; }

        public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
        {
            /* iCloud  capability start */
            application.RegisterForRemoteNotifications();
            PublicDatabase = CKContainer.DefaultContainer.PublicCloudDatabase;
            PrivateDatabase = CKContainer.DefaultContainer.PrivateCloudDatabase;
            /* iCloud  capability end */

            Window = new UIWindow(UIScreen.MainScreen.Bounds);
            var setup = new Setup(this, Window); 
            
            setup.Initialize();

            var startup = Mvx.Resolve<IMvxAppStart>();
            startup.Start();

            Window.MakeKeyAndVisible();


            // Register your app for remote notifications.
            if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                // iOS 10 or later
                var authOptions = UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound;
                UNUserNotificationCenter.Current.RequestAuthorization(authOptions, (granted, error) =>
                {
                    //Console.WriteLine(granted);
                    //Mvx.Warning("granted");
                });

                UNUserNotificationCenter.Current.Delegate = this;

                //Messaging.SharedInstance.RemoteMessageDelegate = this;
            }
            else
            {
                // iOS 9 or before
                var allNotificationTypes = UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound;
                var settings = UIUserNotificationSettings.GetSettingsForTypes(allNotificationTypes, null);
                UIApplication.SharedApplication.RegisterUserNotificationSettings(settings);
            }

            //Firebase.Analytics.App.Configure();
            UIApplication.SharedApplication.RegisterForRemoteNotifications();
            Firebase.InstanceID.InstanceId.Notifications.ObserveTokenRefresh((sender, e) =>
            {
                var newToken = Firebase.InstanceID.InstanceId.SharedInstance.Token;
                // if you want to send notification per user, use this token
                System.Diagnostics.Debug.WriteLine(newToken);

                connectFCM();
            });

            return true;
        }

        private void connectFCM()
        {
            //Messaging.SharedInstance.ShouldEstablishDirectChannel = true;
            Messaging.SharedInstance.Connect((error) =>
            {
                if (error == null)
                {
                    Messaging.SharedInstance.Subscribe("/topics/all");
                }
                System.Diagnostics.Debug.WriteLine(error != null ? "error occured" : "connect success");
            });
        }

        //iOS 9 <=, fire when recieve notification foreground
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            Messaging.SharedInstance.AppDidReceiveMessage(userInfo);

            // Generate custom event
            NSString[] keys = { new NSString("Event_type") };
            NSObject[] values = { new NSString("Recieve_Notification") };
            var parameters = NSDictionary<NSString, NSObject>.FromObjectsAndKeys(keys, values, keys.Length);

            // Send custom event
            Firebase.Analytics.Analytics.LogEvent("CustomEvent", parameters);

            if (application.ApplicationState == UIApplicationState.Active)
            {
                System.Diagnostics.Debug.WriteLine(userInfo);
                var aps_d = userInfo["aps"] as NSDictionary;
                var alert_d = aps_d["alert"] as NSDictionary;
                var body = alert_d["body"] as NSString;
                var title = alert_d["title"] as NSString;
                //debugAlert(title, body);
            }
        }

        // iOS 10, fire when recieve notification foreground
        [Export("userNotificationCenter:willPresentNotification:withCompletionHandler:")]
        public void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
        {
            var title = notification.Request.Content.Title;
            var body = notification.Request.Content.Body;
            //debugAlert(title, body);
        }

        public void ApplicationReceivedRemoteMessage(RemoteMessage remoteMessage)
        {
            //Console.WriteLine(remoteMessage.AppData);
            Mvx.Warning(remoteMessage.AppData.ToString());
        }

        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
#if DEBUG
            Firebase.InstanceID.InstanceId.SharedInstance.SetApnsToken(deviceToken, Firebase.InstanceID.ApnsTokenType.Sandbox);
#endif
#if RELEASE
                        			Firebase.InstanceID.InstanceId.SharedInstance.SetApnsToken(deviceToken, Firebase.InstanceID.ApnsTokenType.Prod);
#endif
        }

        public override void OnResignActivation(UIApplication application)
        {
            // Invoked when the application is about to move from active to inactive state.
            // This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) 
            // or when the user quits the application and it begins the transition to the background state.
            // Games should use this method to pause the game.
        }

        public override void DidEnterBackground(UIApplication application)
        {
            // Use this method to release shared resources, save user data, invalidate timers and store the application state.
            // If your application supports background exection this method is called instead of WillTerminate when the user quits.
            //Messaging.SharedInstance.Disconnect();

            Settings.AppBackGroundTime = DateTime.Now;
        }

        public override void WillEnterForeground(UIApplication application)
        {
            // Called as part of the transiton from background to active state.
            // Here you can undo many of the changes made on entering the background.
            
            if (Settings.LogoutTimeId > 0 && Settings.AppBackGroundTime != DateTime.MinValue)
            {
                int timeDiff = DateTime.Now.Subtract(Settings.AppBackGroundTime).Minutes;
                if (timeDiff >= Settings.LogoutTimeId)
                {
                    var viewModelRequest = new MvxViewModelRequest(typeof(Core.ViewModels.LoginViewModel));
                    var view = (IMvxIosView)UIStoryboard.FromName("Tasks", null).InstantiateViewController("LoginView");
                    var viewController = view.CreateViewControllerFor(viewModelRequest) as UIViewController;
                    UINavigationController nav = (UINavigationController)Window.RootViewController;
                    nav.PushViewController(viewController, true);
                }
            }
            Settings.AppBackGroundTime = DateTime.MinValue;
        }

        public override void OnActivated(UIApplication application)
        {
            // Restart any tasks that were paused (or not yet started) while the application was inactive. 
            // If the application was previously in the background, optionally refresh the user interface.
        }

        public override void WillTerminate(UIApplication application)
        {
            // Called when the application is about to terminate. Save data, if needed. See also DidEnterBackground.
        }

        /* iCloud  capability start */
        //public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        //{
        //    Console.WriteLine("Registered for Push notifications with token: {0}", deviceToken);
        //}

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            Console.WriteLine("Push subscription failed");
        }

        public override void ReceivedRemoteNotification(UIApplication application, NSDictionary userInfo)
        {
            Console.WriteLine("Push received");
        }
        /* iCloud  capability end */
    }`

**Comment by SotoiGhost** [comment] 2018-09-05 03:14
Closing due it seems to be a duplicate of issue #158. Please, keep an eye on #158 to see if something can help you to solve this issue. If you feel that this is a different issue, feel free to re-open it.

**Closed by SotoiGhost** 2018-09-05 03:14 UTC
Labels: assigned engineer
