### ISSUE TITLE
 GoogleTagManager warning: Can not retrieve container from network. Response: 404

### ISSUE THREAD

**Issue by JoacimWall** [xamarin/GoogleApisForiOSComponents#203] opened 2018-11-16 12:18 UTC
When i change from version 6.0.0.3 to 7.1.1 i get this when i start the app. 

Debug output
```
2018-11-16 13:13:51.069 LiberoClub.iOS[13305:3059303] critical: 
Native stacktrace:
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	0   LiberoClub.iOS                      0x00000001056baf5c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 78785240
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	1   LiberoClub.iOS                      0x00000001056c811c mono_pmip + 13872
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	2   libsystem_platform.dylib            0x00000001fc720a20 <redacted> + 56
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	3   JavaScriptCore                      0x0000000203e8af30 JSStringCreateWithCFString + 40
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	4   JavaScriptCore                      0x0000000203debcc8 <redacted> + 40
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	5   LiberoClub.iOS                      0x0000000100c47e3c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 719288
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	6   LiberoClub.iOS                      0x0000000100c3e354 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_
tEPy + 679632
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	7   libdispatch.dylib                   0x00000001fc54d6c8 <redacted> + 24
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	8   libdispatch.dylib                   0x00000001fc54e484 <redacted> + 16
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	9   libdispatch.dylib                   0x00000001fc528fb0 <redacted> + 548
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	10  libdispatch.dylib                   0x00000001fc529af4 <redacted> + 412
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	11  libdispatch.dylib                   0x00000001fc531f14 <redacted> + 584
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	12  libsystem_pthread.dylib             0x00000001fc7300dc _pthread_wqthread + 312
2018-11-16 13:13:51.074 LiberoClub.iOS[13305:3059303] critical: 	13  libsystem_pthread.dylib             0x00000001fc732cec start_wqthread + 4
2018-11-16 13:13
:51.074 LiberoClub.iOS[13305:3059303] critical: 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
The app has been terminated.
Failed to Stop app:  An error occured on client IDB4110779 while executing a reply for topic xvs/idb/4.11.0.779/stop-app
The app has been terminated.
```
```
 <ItemGroup>
    <PackageReference Include="Acr.UserDialogs">
      <Version>7.0.1</Version>
    </PackageReference>
    <PackageReference Include="CarouselView.FormsPlugin">
      <Version>5.2.0</Version>
    </PackageReference>
    <PackageReference Include="DLToolkit.Forms.Controls.FlowListView">
      <Version>2.0.11</Version>
    </PackageReference>
    <PackageReference Include="DLToolkit.Forms.Controls.ImageCropView">
      <Version>1.0.7</Version>
    </PackageReference>
    <PackageReference Include="LiveXAML">
      <Version>2.1.50</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter">
      <Version>1.10.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>1.10.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Distribute">
      <Version>1.10.0</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Settings">
      <Version>4.0.0.10-beta</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Build.Download">
      <Version>0.4.11</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>0.11.0-preview</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms">
      <Version>3.4.0.1008975</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Media">
      <Version>4.0.1.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.CloudMessaging">
      <Version>3.1.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.iOS.Analytics">
      <Version>3.17.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.iOS.TagManager">
      <Version>7.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.TestCloud.Agent">
      <Version>0.21.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.Analytics">
      <Version>5.1.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.Core">
      <Version>5.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.InstanceID">
      <Version>3.2.1</Version>
    </PackageReference>
    <PackageReference Include="Plugin.Permissions">
      <Version>3.0.0.12</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by SotoiGhost** [comment] 2018-11-16 19:18
Closing this due is a duplicate of issue #202

**Closed by SotoiGhost** 2018-11-16 19:18 UTC
