### ISSUE TITLE
`GaiConstants` values are all null in iOS app extension

### ISSUE THREAD

**Issue by kspearrin** [xamarin/GoogleApisForiOSComponents#116] opened 2017-12-14 05:13 UTC
Pretty weird behavior here, but whenever we updated `Xamarin.Google.iOS.Analytics` from version 3.17.0.1 => 3.17.0.2 our action app extension started breaking. Upon further investigation we find that this line in our code is the problem:

```
_tracker.Set(GaiConstants.ScreenName, pageName);
```

It throws an `ArgumentNullException`:

> 'parameterName' cannot be null.

Debugging the line shows that _all values_ in `GaiConstants` are null.

This only seems to happen from our app extension and not the main app. The only difference between the build that does work and the build that does not work is updating from version 3.17.0.1 => 3.17.0.2.

Any ideas?

Project for reference: https://github.com/bitwarden/mobile

**Comment by SotoiGhost** [comment] 2017-12-14 19:15
@kspearrin can you share an isolated test case with the problem, please? That would help us to speed up the process to find out if this is a bug in the tool.

**Comment by kspearrin** [comment] 2017-12-15 03:32
@SotoiGhost I've narrowed this down further to the `Xamarin.Build.Download` dependency. I can leave `Xamarin.Google.iOS.Analytics` at version 3.17.0.1 and just install `Xamarin.Build.Download` version 0.4.7 and the same problem occurs. Without installing `Xamarin.Build.Download` explicitly you get version `0.4.3` which doesn't appear to have this issue.

I'll see if I can put together an isolated test project.

**Comment by kspearrin** [comment] 2017-12-16 14:53
@SotoiGhost I created a trimmed down version of our app here that just has a simple Forms page with the iOS app extension. Strangely enough, with this version it seems to occur even with v3.17.0.1 as well. Seems very inconsistent, but it's definitely still happening here even with all the other noise from the app removed.

https://github.com/kspearrin/BuildDownloadTest


Just set your breakpoint here when launching the extension:

https://github.com/kspearrin/BuildDownloadTest/blob/master/src/iOS.Extension/LoadingViewController.cs#L19

**Comment by SotoiGhost** [comment] 2017-12-18 22:05
@kspearrin For me is working. I tested your test case on Simulator with iOS 11.2, 11.0.2, 10.3.1 and 9.3 and worked for me:

![image](https://user-images.githubusercontent.com/5924210/34129694-a65c6d12-e40a-11e7-99f2-821ad3b5ce04.png)

I couldn't test it on a real device because is asking me for a provisioning profile with certain entitlements enabled (even disabling all of them, keeps asking me something else). So, I created a quick sample, tested it on an iPhone 7 with iOS 11.1.2 and worked for me:

![image](https://user-images.githubusercontent.com/5924210/34130263-caf75f54-e40c-11e7-939f-7249b69e5dba.png)

What was your environment test?

**Comment by kspearrin** [comment] 2017-12-18 22:13
That's weird. I am testing on an iPhone 6s device, macOS with VS 2017. Did you try updating `Xamarin.Google.iOS.Analytics` to 3.17.0.2?

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3 (build 799)
Installation UUID: 15eeb07b-27a3-4e5d-b35e-edfee3d0f28c
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.3/Sdks
SDK Versions:
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.2 (Visual Studio Enterprise)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Build Information ===

Release ID: 703000799
Git revision: df590420ea5bc681994baefff2eabdaad889fba9
Build date: 2017-12-05 09:23:45-05
Xamarin addins: 51068d6eaf3b6fb4fbc72b33cb869b0ebff04ec5
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

```

**Comment by SotoiGhost** [comment] 2017-12-18 22:43
I have the same result updating to most recent version. Can you try deleting the bin and obj folder, removing the app from your device and reinstalling it?

**Comment by kspearrin** [comment] 2017-12-19 01:23
I just tested this with a fresh pull from the GitHub repo. I run it using the iPhone 8 simulator and it works correctly on 3.17.0.1 and 3.17.0.2. No values are null.

However, whenever I deploy it to my iPhone 6S device (previously app uninstalled completely) it works on `3.17.0.1` but when I update to `3.17.0.2` (clearing bin and obj after, and uninstalling previous deployed app) I get null values on all `GaiConstants` properties.

**Comment by SotoiGhost** [comment] 2017-12-19 01:45
So, just to be clear. The steps to reproduce the bug are:

1. Have installed G.Analytics v3.17.0.1 package in fresh project
2. Run the project for the first time on a device
3. Update the package to v3.17.0.2
4. Clean the project, clear bin and debug folders and uninstall the app
5. Run the project on a device

Right?

Another thing, what happens if you make a fresh pull, update the package to v3.17.0.2 and then run it for the first time on a device?

**Comment by SotoiGhost** [comment] 2017-12-19 02:16
Hmm… I cannot reproduce the bug… this is weird.

**Comment by kspearrin** [comment] 2017-12-19 02:33
I just updated the GitHub repo to v3.17.0.2.

1. Pull refresh copy of repo.
2. Uninstall any previous version of the app from device.
3. Set breakpoint in LoadingViewController
4. Deploy iOS.Extension -> Debug - iPhone -> My iPhone 6S
5. Launch extension from a Safari website share menu.
6. Observe nulls at breakpoint.

**Comment by kspearrin** [comment] 2017-12-19 02:36
I'm just guessing here, but maybe it has something to do with this app id being previously installed on my device (the real app)?

**Comment by SotoiGhost** [comment] 2017-12-19 03:15
Mmm… I cannot install the test case on a device, keeps saying that something is not well configured.

![image](https://user-images.githubusercontent.com/5924210/34139116-7432a666-e438-11e7-8fe8-66b965a24ee8.png)

Even disabling all of the Entitlements, keeps throwing me that I cannot install the app, am I missing something?

**Comment by kspearrin** [comment] 2017-12-19 03:27
Welcome to provisioning hell 😭 . I think iCloud and Push Notifications should be enabled.

Here is main app:

![image](https://user-images.githubusercontent.com/1190944/34139363-58460fa6-e442-11e7-9238-1d83ea1f7896.png)


Extension:

![image](https://user-images.githubusercontent.com/1190944/34139375-6fc6ac08-e442-11e7-8e06-23c48f4177d7.png)

**Comment by SotoiGhost** [comment] 2017-12-19 03:28
Ohh… Push Notifications, I think that's the problem, let me check

**Comment by SotoiGhost** [comment] 2017-12-19 03:43
Yep, that was the problem, needed to remove a key on Info.plist about the remote notifications in the background. Also, I can see the `null` values. Let me deep in into this.

**Comment by kspearrin** [comment] 2017-12-19 03:47
Hooray, I'm not crazy!

**Comment by SotoiGhost** [comment] 2017-12-19 08:00
@kspearrin Please, try changing the linker behavior of you iOS extension app. Open your extension project settings, go to **iOS Build**, and change **Link behavior** from **Don't Link** to **Link Framework SDKs Only** and let me know your results. Thanks in advance :)

**Comment by kspearrin** [comment] 2017-12-19 13:41
@SotoiGhost Yes, that seems to fix it.

![screen shot 2017-12-19 at 8 40 35 am](https://user-images.githubusercontent.com/1190944/34159758-4f88a6c0-e498-11e7-9364-50d5ef349fa1.png)

Seems pretty odd that linking would fix the issue. Usually it's the other way around.

**Comment by SotoiGhost** [comment] 2017-12-19 16:32
Yes, I know… I had the same thought. Glad to read that this worked for you.

After playing with some iOS configuration and different kind of projects, I have come to the conclusion that this is an odd scenario caused by Xamarin.Forms, NetStandard, and the linker that affects only G.Analytics, I tried using Firebase.Analytics and everything worked as expected. Please, if you can, [file an issue][1](https://github.com/xamarin/Xamarin.Forms/issues/new) in Xamarin.Forms GitHub repo, explaining what's happening.

I'm closing this issue now. If something else happens related with this, feel free to re-open this issue.

Best!

**Closed by SotoiGhost** 2017-12-19 16:32 UTC
