### ISSUE TITLE
dyld: Library not loaded: @rpath/protobuf.framework/protobuf

### ISSUE THREAD

**Issue by moustafashaban** [xamarin/GoogleApisForiOSComponents#322] opened 2019-10-21 07:39 UTC
Xamarin.Firebase.iOS.CloudMessaging

After upgrading to 4.1.1 the debugger in VS for mac closed immediately and give the following message: 

dyld: Library not loaded: @rpath/protobuf.framework/protobuf
  Referenced from: /private/var/containers/Bundle/Application/499E88A7-FD47-4C14-B204-398FD6C615C8/XF_Mushref.iOS.app/Frameworks/FirebaseMessaging.framework/FirebaseMessaging
  Reason: image not found

**Comment by SotoiGhost** [comment] 2019-10-22 18:55
This seems to be a duplicate of #311. Closing this issue.

**Closed by SotoiGhost** 2019-10-22 18:55 UTC
