### ISSUE TITLE
Build errors with any Google API for iOS

### ISSUE THREAD

**Issue by AmirMahdiNassiri** [xamarin/GoogleApisForiOSComponents#381] opened 2020-03-06 18:39 UTC
My project builds perfectly fine when I do not add a reference to Xamarin.Firebase packages, but when I do, I get the error "Could not load file or assembly 'Microsoft.Win32.Registry" while building the project. I have tried different Xamarin.Build.Download versions 0.4.11, 0.7.1, 0.8, 0.9, and finally 0.10. None of them solved my problem! I have tried clearing the .nuget cache, as well as bin and obj folders. Still no hope!

I am using Visual Studio on Windows, and connecting to my Mac via the LAN. I have also cleared the .nuget cache from my Mac. Also, I am installing the latest version of Xamarin.Firebase.iOS.Core v6.6.0.

As I read through the related issues for other Google API packages ( #365 or #372 ) others have reported the same build errors as I am getting.

**Comment by Minneth** [comment] 2020-03-06 19:05
Seconded. I'm experiencing the exact same issue. Found myself going around in circles, it seems the new 0.10 gives:

The "XamarinDownloadArchives" task could not be initialized with its input parameters.

And the previous versions give either the Win32 error or Sharing Violation errors.

**Comment by SotoiGhost** [comment] 2020-03-06 19:08
@AmirMahdiNassiri @Minneth Can you share a test case, please? We have tested again XBD and seems to be working ok from our side.

**Comment by AmirMahdiNassiri** [comment] 2020-03-06 19:41
@SotoiGhost Yes, of course. I even created a new Xamarin Forms solution using Visual Studio 2019, and only added the Xamarin.Firebase.iOS.Core v6.6.0. I'm getting a bunch of "MT5210: Native linking failed". I have saved them in the attached build log file.

Please let me know if any additional data is required.

[Build Log.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/4300126/Build.Log.txt)

**Comment by SotoiGhost** [comment] 2020-03-06 20:24
@AmirMahdiNassiri Can you add the following line to your test case please? Let me know your results.

```
Firebase.Core.App.Configure();
```

**Comment by AmirMahdiNassiri** [comment] 2020-03-06 20:44
@SotoiGhost Oh, I can confirm that putting this line in `AppDelegate.FinishedLaunching` ensures a successful build! Thank you so much for your amazingly quick replies! My apologies that I didn't know this is a requirement for a successful build.

Have a great day, and keep up the great work.

**Comment by AmirMahdiNassiri** [comment] 2020-03-06 20:55
@SotoiGhost Sadly, after putting my next line of code, which is `Crashlytics.Configure();` the error reappears! I tried clearing obj and bin directories and installed Xamarin.Build.Download v0.10 on the iOS project.

**Comment by Minneth** [comment] 2020-03-06 21:14
I've already got this in my code and no benefit, unfortunately.
________________________________

**Comment by SotoiGhost** [comment] 2020-03-06 22:11
@AmirMahdiNassiri I added `Crashlytics.Configure();` and worked for me. The only thing that might differ is the environment data. Are you up to date on stable channel?

**Comment by AmirMahdiNassiri** [comment] 2020-03-06 22:17
@SotoiGhost Yes, you're right. It worked after clearing obj and bin and restarting Visual Studio! What's the problem with those native linkings?!

**Comment by SotoiGhost** [comment] 2020-03-06 22:35
Glad to know that this is working!

The problem is that Firebase and Google have a quite complex dependency chain (by dependency I mean `GoogleUtilities`, `Protobuf`, `GTMSessionFetcher`, etc.), so, the linker tries to do it best to remove unused code to reduce app size. But, the linker is not perfect and makes mistakes sometimes (even more when native frameworks use swizzling as Firebase does), so it strips dependency symbols thinking that no-one use them, but Firebase frameworks use them somehow and viceversa. That's the reason of Firebase linking errors even when you haven't coded anything.

I'm closing this issue as it seems that the error is fixed. If you still facing something related to this, please, feel free to reopen it! Happy coding!

**Closed by SotoiGhost** 2020-03-06 22:35 UTC
Labels: needs-info

**Comment by AmirMahdiNassiri** [comment] 2020-03-06 22:39
@SotoiGhost I see. It's not the first time for me that the linking process does annoying things. Entity Framework core had some issues with the linking process as well!

Thank you for all the information, and I really appreciate all your quick replies. Happy coding!

**Comment by uptowndat777777** [comment] 2020-03-09 10:34
Hello, Compliment of the day, how are you today ? i am Happy to get together with you,My name is Serach , I'm a military medical nurse from israel. Please let not my profession, race or nationality inch your mind, I have gone across your profile and became interested in you, we can be good friends, contact me through my private email address/  //abelmans@aol.com   ////
