### ISSUE TITLE
Unable to use on SpriteKit project, causes native linking to fail

### ISSUE THREAD

**Issue by JamesRoche** [xamarin/GoogleApisForiOSComponents#9] opened 2016-05-25 16:52 UTC
Unable to use on Google Ads on SpriteKit project, causes native linking to fail

Trying o use on a standard new SpriteKit project but its causing the following errors on build. This only applies on physical devices, simulator is unaffected.

		clang: error: linker command failed with exit code 1 (use -v to see invocation)
		
MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: CAMediaTimingFunction. The symbol '_OBJC_CLASS_$_CAMediaTimingFunction' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: CATransaction. The symbol '_OBJC_CLASS_$_CATransaction' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: CATransition. The symbol '_OBJC_CLASS_$_CATransition' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH: error MT5210: Native linking failed, undefined symbol: _kCATransitionFromTop. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: _kCAMediaTimingFunctionEaseInEaseOut. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: _kCATransitionPush. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: _CATransform3DMakeRotation. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5210: Native linking failed, undefined symbol: _CACurrentMediaTime. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH: error MT5202: Native linking failed. Please review the build log.

**Comment by scordonnier** [comment] 2016-05-25 20:07
I had the same issue last week when I tried to recompile the source code I had downloaded from GitHub.

I've solved the issue by modifying the file named "GoogleMobileAds.linkwith.cs" and by adding "QuartzCore" in the framework list (cf. below).

`[assembly: LinkWith ("GoogleMobileAds", LinkTarget.ArmV7 | LinkTarget.ArmV7s | LinkTarget.Arm64 | LinkTarget.Simulator | LinkTarget.Simulator64, LinkerFlags = "-ObjC", Frameworks = "AdSupport AudioToolbox AVFoundation CoreBluetooth CoreGraphics CoreMedia CoreTelephony EventKit EventKitUI MediaPlayer MessageUI QuartzCore SafariServices StoreKit SystemConfiguration", ForceLoad = true, SmartLink = true)]`

**Comment by JamesRoche** [comment] 2016-05-25 20:09
Seriously appreciate the help, i am very new to this low level stuff though. I was trying doc smile it from the source using the help on the ready but got stuck with the cake script. Any chance you can email me over your working copy? me@james-roche.co.uk would save me lots of trouble!

**Comment by SotoiGhost** [comment] 2016-07-19 23:38
I can reproduce this issue creating a new SpriteKit app.

Adding QuartzCore to Frameworks resolve this issue as @scordonnier said.

The fix will be released in version 7.8.1.0

**Comment by bbartlett** [comment] 2016-07-28 20:57
@SotoiGhost Any idea when version 7.8.1.0 will be available?  Looks like this issue also impacts using this component in Xamarin.Forms and/or Xamarin.Forms.Maps.  (I'm hitting the same problem in a Xamarin.Forms mapping app and I'm not using SpriteKit, although I have a custom renderer for the BannerView.)  I'd prefer to not deal with the whole "cake" setup and building, but at the moment, looks like my ability to release this app is dead in the water...

**Comment by SotoiGhost** [comment] 2016-08-09 22:48
Version 7.8.1.0 is available on store.

https://components.xamarin.com/view/googleiosmobileads

**Closed by SotoiGhost** 2016-08-09 22:48 UTC
Labels: bug
