### ISSUE TITLE
IMapViewDelegate method not getting called "UIView MarkerInfoWindow(MapView mv,Marker m)"

### ISSUE THREAD

**Issue by aproram** [xamarin/GoogleApisForiOSComponents#99] opened 2017-10-28 12:57 UTC
On Xamarin iOS I have a map which has markers. I want to have a custom Info View but the problem is that the delegate method "UIView MarkerInfoWindow(MapView mv,Marker m)" for the IMapViewDelegate  doesn't get called somehow. I have no idea whats the problem.

I have uploaded one simple repo demonstrating this problem at
https://github.com/aproram/Xamarin-GMapsDelegate-IssueDemo

Any idea why this is happening and the method doesn't get called ?

**Comment by SotoiGhost** [comment] 2017-11-22 22:39
@aproram For me is working. I tested on the simulator with iOS 11 and on devices with iOS 11 and iOS 9. Here are some screenshots:

<img src="https://user-images.githubusercontent.com/5924210/33152105-857a6b90-cfa0-11e7-9658-c14e47528079.png" width=320 height=580 />

<img src="https://user-images.githubusercontent.com/5924210/33152125-a47e748c-cfa0-11e7-905d-4379ae4e6173.png" width=320 height=580 />

**Comment by SotoiGhost** [comment] 2018-01-25 23:21
Closing this issue due to the issue cannot be reproducible. If you are still experiencing this issue feel free to re-open the issue report. Thanks!

**Closed by SotoiGhost** 2018-01-25 23:21 UTC
