### ISSUE TITLE
undefined Objective-C class: GSDK_GTMStringEncoding

### ISSUE THREAD

**Issue by aphex3k** [xamarin/GoogleApisForiOSComponents#61] opened 2017-01-14 00:57 UTC
when including Xamarin.Firebase.iOS.Core as package reference Xamarin fails compiling with

    MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: GSDK_GTMStringEncoding. The symbol '_OBJC_CLASS_$_GSDK_GTMStringEncoding' could not be found in any of the libraries or frameworks linked with your application.

**Comment by SotoiGhost** [comment] 2017-01-17 18:55
Hi @aphex3k, can you give me a list of your NuGet and version referenced to your project?

**Comment by aphex3k** [comment] 2017-01-17 19:02
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Xamarin.Build.Download" version="0.4.1" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Analytics" version="3.6.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.Core" version="3.4.5" targetFramework="xamarinios10" />
  <package id="Xamarin.Firebase.iOS.InstanceID" version="1.0.8" targetFramework="xamarinios10" />
  <package id="Xamarin.Google.iOS.Analytics" version="3.17.0" targetFramework="xamarinios10" />
  <package id="Xamarin.Google.iOS.TagManager" version="5.0.6.2" targetFramework="xamarinios10" />
</packages>
```

**Comment by aphex3k** [comment] 2017-01-17 19:07
You can download my test Xamarin project here: http://cloud1.codingmerc.com/test.zip

**Comment by SotoiGhost** [comment] 2017-01-17 19:12
Thx for the test case, let me review it.

**Comment by SotoiGhost** [comment] 2017-01-17 20:51
@aphex3k the problem is with Google.TagManager, seems to be not compatible with Firebase.Analytics and Firebase.Core. Google.TagManager seems to be looking for old dependencies. I will work on the update. For now TagManager is stuck. Sorry for the inconveniences that this cause.

**Comment by aphex3k** [comment] 2017-01-20 23:27
Is there any eta for the fix available or any possibility to expedite a solution?

**Comment by SotoiGhost** [comment] 2017-02-03 19:37
Google Tag Manager for iOS version 5.0.8 is now live. I'll close this issue. Feel free to reopen it if the issue reappears.

**Closed by SotoiGhost** 2017-02-03 19:37 UTC
Labels: bug

**Comment by SomeShapa** [comment] 2017-02-27 13:04
@SotoiGhost, hi!
I've got similar error when i tried to use Remote Configs.
`C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBDescriptorRoot. The symbol '_OBJC_CLASS_$_GSDK_PBDescriptorRoot' could not be found in any of the libraries or frameworks linked with your application.`

Can you help?

Log:
```
1>------ Rebuild All started: Project: FirebaseFeaturesTest, Configuration: Debug Any CPU ------
1>  FirebaseFeaturesTest -> D:\Projects\FirebaseFeaturesTest\FirebaseFeaturesTest\FirebaseFeaturesTest\bin\Debug\FirebaseFeaturesTest.dll
2>------ Rebuild All started: Project: FirebaseFeaturesTest.iOS, Configuration: Debug iPhone ------
2>  Generated session id: fcf60391d3126aeb5e2761ff67b781a5
2>  Generated build app name: FirebaseFeaturesTest.iOS
2>  Connecting to Mac server 172.20.65.48...
2>D:\Projects\FirebaseFeaturesTest\FirebaseFeaturesTest\FirebaseFeaturesTest.iOS\AppDelegate.cs(42,17,42,23): warning CS0168: The variable 'status' is declared but never used
2>D:\Projects\FirebaseFeaturesTest\FirebaseFeaturesTest\FirebaseFeaturesTest.iOS\AppDelegate.cs(38,28,38,49): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
2>  FirebaseFeaturesTest.iOS -> D:\Projects\FirebaseFeaturesTest\FirebaseFeaturesTest\FirebaseFeaturesTest.iOS\bin\iPhone\Debug\FirebaseFeaturesTest.iOS.exe
2>  Detected signing identity:
2>    Code Signing Key: "iPhone Developer: Pavel Shchipitsyn (SWHQD5RKE8)" (1D2963BF1B11AE045157C10D6A8706F9354E2A1E)
2>    Provisioning Profile: "Firebase features test provisioning profile" (8ee1ea55-78d1-4964-a0c6-756302002074)
2>    Bundle Id: com.itransition.FNT
2>    App Id: NCJC54GM5Z.com.itransition.FNT
2>  Process exited with code 1, command:
2>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -framework UIKit -framework Foundation -framework QuartzCore -framework CoreGraphics -framework GLKit -framework OpenGLES -framework Security -weak_framework CoreSpotlight -weak_framework CloudKit -weak_framework CFNetwork -weak_framework CoreFoundation /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/FirebaseRemoteConfig /Library/Frameworks/Xamarin.iOS.framework/Versions/10.3.1.7/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmonosgen-2.0.a /Library/Frameworks/Xamarin.iOS.framework/Versions/10.3.1.7/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libxamarin-debug.a /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/FirebaseFeaturesTest.iOS.exe.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/mscorlib.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/Xamarin.iOS.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/System.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/System.Xml.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/System.Core.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/Mono.Dynamic.Interpreter.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/Xamarin.Forms.Platform.iOS.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/Xamarin.Forms.Core.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/Xamarin.Forms.Platform.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/System.Net.Http.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/System.Runtime.Serialization.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/System.ServiceModel.Internals.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/Firebase.RemoteConfig.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/FirebaseFeaturesTest.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/Xamarin.Forms.Xaml.dll.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/registrar.arm64.o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/main.arm64.o -force_load /Library/Frameworks/Xamarin.iOS.framework/Versions/10.3.1.7/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libapp.a -lsqlite3 -lz -Wl,-pie -arch arm64 -miphoneos-version-min=6.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -lz -o /Users/user/Library/Caches/Xamarin/mtbs/builds/FirebaseFeaturesTest.iOS/fcf60391d3126aeb5e2761ff67b781a5/obj/iPhone/Debug/mtouch-cache/64/Output/FirebaseFeaturesTest.iOS -liconv -dead_strip -u _CreateZStream -u _CloseZStream -u _Flush -u _ReadZStream -u _WriteZStream -u _xamarin_start_wwan -u _xamarin_get_block_descriptor -u _xamarin_IntPtr_objc_msgSend_IntPtr -u _xamarin_IntPtr_objc_msgSendSuper_IntPtr -u _UIApplicationMain -u _xamarin_timezone_get_data -u _xamarin_GetFolderPath -u _xamarin_log -u _FIRRemoteConfigErrorDomain -u _FIRNamespaceGoogleMobilePlatform -u _FIRRemoteConfigThrottledEndTimeInSecondsKey -u _mono_pmip
2>  Undefined symbols for architecture arm64:
2>    "_OBJC_CLASS_$_GSDK_PBDescriptorRoot", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        objc-class-ref in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>    "_OBJC_CLASS_$_GSDK_PBExtensionField", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        objc-class-ref in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>    "_OBJC_CLASS_$_GSDK_PBGeneratedEnumDescriptor", referenced from:
2>        _OBJC_CLASS_$_RCNConfigDeviceTypeEnumDescriptor in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNAppNamespaceConfigTable_NamespaceStatusEnumDescriptor in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNConfigFetchResponse_ResponseStatusEnumDescriptor in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_ConfigFetchReason_AndroidConfigFetchTypeEnumDescriptor in FirebaseRemoteConfig(AndroidConfig.pb_de9a4fec71749e51939025d92ede41f6.o)
2>        _OBJC_CLASS_$_RCNIdentifierTypeEnumDescriptor in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        _OBJC_CLASS_$_GINSemanticTypeEnumDescriptor in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        _OBJC_CLASS_$_GINDataFormatEnumDescriptor in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        ...
2>    "_OBJC_CLASS_$_GSDK_PBRootObject", referenced from:
2>        _OBJC_CLASS_$_RCNConfigRoot in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_AndroidConfigRoot in FirebaseRemoteConfig(AndroidConfig.pb_de9a4fec71749e51939025d92ede41f6.o)
2>        _OBJC_CLASS_$_RCNLogsAnnotationsRoot in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        _OBJC_CLASS_$_GINSemanticAnnotationsRoot in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        _OBJC_CLASS_$_GINRetentionAnnotationsRoot in FirebaseRemoteConfig(RetentionAnnotations.pb_31032757ee40b2f36d356bd485b9d8f1.o)
2>    "_OBJC_METACLASS_$_GSDK_PBRootObject", referenced from:
2>        _OBJC_METACLASS_$_RCNConfigRoot in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_AndroidConfigRoot in FirebaseRemoteConfig(AndroidConfig.pb_de9a4fec71749e51939025d92ede41f6.o)
2>        _OBJC_METACLASS_$_RCNLogsAnnotationsRoot in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        _OBJC_METACLASS_$_GINSemanticAnnotationsRoot in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        _OBJC_METACLASS_$_GINRetentionAnnotationsRoot in FirebaseRemoteConfig(RetentionAnnotations.pb_31032757ee40b2f36d356bd485b9d8f1.o)
2>    "_OBJC_METACLASS_$_GSDK_PBGeneratedMessage", referenced from:
2>        _OBJC_METACLASS_$_RCNPackageData in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNKeyValue in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNNamedValue in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNConfigFetchRequest in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNPackageTable in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNAppNamespaceConfigTable in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNAppConfigTable in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        ...
2>    "_OBJC_CLASS_$_GSDK_PBDescriptor", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        objc-class-ref in FirebaseRemoteConfig(AndroidConfig.pb_de9a4fec71749e51939025d92ede41f6.o)
2>        objc-class-ref in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        objc-class-ref in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        objc-class-ref in FirebaseRemoteConfig(RetentionAnnotations.pb_31032757ee40b2f36d356bd485b9d8f1.o)
2>    "_OBJC_CLASS_$_FIRInstanceID", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(RCNConfigFetch_bc851f8fb57d604ee3a06f3110c72c4c.o)
2>    "_OBJC_CLASS_$_GSDK_PBEnumDescriptor", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        objc-class-ref in FirebaseRemoteConfig(AndroidConfig.pb_de9a4fec71749e51939025d92ede41f6.o)
2>        objc-class-ref in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        objc-class-ref in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        objc-class-ref in FirebaseRemoteConfig(RetentionAnnotations.pb_31032757ee40b2f36d356bd485b9d8f1.o)
2>    "_OBJC_CLASS_$_GSDK_PBObjectivecDescriptorRoot", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        objc-class-ref in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        objc-class-ref in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        objc-class-ref in FirebaseRemoteConfig(RetentionAnnotations.pb_31032757ee40b2f36d356bd485b9d8f1.o)
2>    "_OBJC_CLASS_$_GSDK_PBExtensionRegistry", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        objc-class-ref in FirebaseRemoteConfig(AndroidConfig.pb_de9a4fec71749e51939025d92ede41f6.o)
2>        objc-class-ref in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        objc-class-ref in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        objc-class-ref in FirebaseRemoteConfig(RetentionAnnotations.pb_31032757ee40b2f36d356bd485b9d8f1.o)
2>    "_OBJC_CLASS_$_GSDK_PBMutableArray", referenced from:
2>        objc-class-ref in FirebaseRemoteConfig(RCNConfigSettings_0ab3f6d0273f41c6645d29f98aa3d22d.o)
2>    "_FIRLogInfo", referenced from:
2>        ___42-[RCNConfigDBManager createOrOpenDatabase]_block_invoke in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        ___81-[RCNConfigFetch refreshInstanceIDTokenAndFetchCheckInInfoWithCompletionHandler:]_block_invoke_2 in FirebaseRemoteConfig(RCNConfigFetch_bc851f8fb57d604ee3a06f3110c72c4c.o)
2>        ___56-[RCNConfigFetch fetchCheckinInfoWithCompletionHandler:]_block_invoke_2 in FirebaseRemoteConfig(RCNConfigFetch_bc851f8fb57d604ee3a06f3110c72c4c.o)
2>        -[RCNConfigAnalytics fetchUserPropertiesWithCompletionHandler:] in FirebaseRemoteConfig(RCNConfigAnalytics_f42150e7d8b5fdb049c74281185407ab.o)
2>    "_GSDK_NSClassFromString", referenced from:
2>        -[RCNConfigAnalytics fetchUserPropertiesWithCompletionHandler:] in FirebaseRemoteConfig(RCNConfigAnalytics_f42150e7d8b5fdb049c74281185407ab.o)
2>    "_OBJC_METACLASS_$_GSDK_PBGeneratedEnumDescriptor", referenced from:
2>        _OBJC_METACLASS_$_RCNConfigDeviceTypeEnumDescriptor in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNAppNamespaceConfigTable_NamespaceStatusEnumDescriptor in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_RCNConfigFetchResponse_ResponseStatusEnumDescriptor in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_METACLASS_$_ConfigFetchReason_AndroidConfigFetchTypeEnumDescriptor in FirebaseRemoteConfig(AndroidConfig.pb_de9a4fec71749e51939025d92ede41f6.o)
2>        _OBJC_METACLASS_$_RCNIdentifierTypeEnumDescriptor in FirebaseRemoteConfig(LogsAnnotations.pb_e6c0c37afc37f9a6fb29dc2d757944d4.o)
2>        _OBJC_METACLASS_$_GINSemanticTypeEnumDescriptor in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        _OBJC_METACLASS_$_GINDataFormatEnumDescriptor in FirebaseRemoteConfig(SemanticAnnotations.pb_3d6e05bb1742046fe24361e82c8aabc0.o)
2>        ...
2>    "_FIRLogDebug", referenced from:
2>        +[RCNConfigFetch setGlobalTestBlock:] in FirebaseRemoteConfig(RCNConfigFetch_bc851f8fb57d604ee3a06f3110c72c4c.o)
2>    "_FIRLogWarning", referenced from:
2>        -[RCNConfigContent copyFromDictionary:toSource:] in FirebaseRemoteConfig(RCNConfigContent_485541adc945691ed9059c46a28fdd5c.o)
2>        -[RCNConfigFetch fetchWithUserProperties:completionHandler:] in FirebaseRemoteConfig(RCNConfigFetch_bc851f8fb57d604ee3a06f3110c72c4c.o)
2>    "_kFIRLoggerRemoteConfig", referenced from:
2>        ___47-[FIRRemoteConfig configValueForKey:namespace:]_block_invoke in FirebaseRemoteConfig(FIRRemoteConfig_8195944d75486247512e83ec94016dc3.o)
2>        ___48-[FIRRemoteConfig defaultValueForKey:namespace:]_block_invoke in FirebaseRemoteConfig(FIRRemoteConfig_8195944d75486247512e83ec94016dc3.o)
2>        -[RCNConfigContent copyFromDictionary:toSource:] in FirebaseRemoteConfig(RCNConfigContent_485541adc945691ed9059c46a28fdd5c.o)
2>        ___42-[RCNConfigDBManager createOrOpenDatabase]_block_invoke in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        -[RCNConfigDBManager removeDatabase:] in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        -[RCNConfigDBManager executeQuery:] in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        -[RCNConfigDBManager insertMainTableWithValues:fromSource:] in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        ...
2>    "_OBJC_CLASS_$_GSDK_PBGeneratedMessage", referenced from:
2>        _OBJC_CLASS_$_RCNPackageData in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNKeyValue in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNNamedValue in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNConfigFetchRequest in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNPackageTable in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNAppNamespaceConfigTable in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        _OBJC_CLASS_$_RCNAppConfigTable in FirebaseRemoteConfig(Config.pb_83dfbeb21b77855eb8209b666595a59f.o)
2>        ...
2>    "_FIRLogError", referenced from:
2>        ___47-[FIRRemoteConfig configValueForKey:namespace:]_block_invoke in FirebaseRemoteConfig(FIRRemoteConfig_8195944d75486247512e83ec94016dc3.o)
2>        ___48-[FIRRemoteConfig defaultValueForKey:namespace:]_block_invoke in FirebaseRemoteConfig(FIRRemoteConfig_8195944d75486247512e83ec94016dc3.o)
2>        -[RCNConfigContent copyFromDictionary:toSource:] in FirebaseRemoteConfig(RCNConfigContent_485541adc945691ed9059c46a28fdd5c.o)
2>        ___42-[RCNConfigDBManager createOrOpenDatabase]_block_invoke in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        -[RCNConfigDBManager removeDatabase:] in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        -[RCNConfigDBManager executeQuery:] in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        -[RCNConfigDBManager insertMainTableWithValues:fromSource:] in FirebaseRemoteConfig(RCNConfigDBManager_c1aa86daa4e06168a3b28858195442ee.o)
2>        ...
2>  ld: symbol(s) not found for architecture arm64
2>  clang: error: linker command failed with exit code 1 (use -v to see invocation)
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBDescriptorRoot. The symbol '_OBJC_CLASS_$_GSDK_PBDescriptorRoot' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBExtensionField. The symbol '_OBJC_CLASS_$_GSDK_PBExtensionField' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBGeneratedEnumDescriptor. The symbol '_OBJC_CLASS_$_GSDK_PBGeneratedEnumDescriptor' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBRootObject. The symbol '_OBJC_CLASS_$_GSDK_PBRootObject' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _OBJC_METACLASS_$_GSDK_PBRootObject. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _OBJC_METACLASS_$_GSDK_PBGeneratedMessage. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBDescriptor. The symbol '_OBJC_CLASS_$_GSDK_PBDescriptor' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: FIRInstanceID. The symbol '_OBJC_CLASS_$_FIRInstanceID' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBEnumDescriptor. The symbol '_OBJC_CLASS_$_GSDK_PBEnumDescriptor' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBObjectivecDescriptorRoot. The symbol '_OBJC_CLASS_$_GSDK_PBObjectivecDescriptorRoot' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBExtensionRegistry. The symbol '_OBJC_CLASS_$_GSDK_PBExtensionRegistry' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBMutableArray. The symbol '_OBJC_CLASS_$_GSDK_PBMutableArray' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _FIRLogInfo. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _GSDK_NSClassFromString. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _OBJC_METACLASS_$_GSDK_PBGeneratedEnumDescriptor. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _FIRLogDebug. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _FIRLogWarning. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _kFIRLoggerRemoteConfig. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined Objective-C class: GSDK_PBGeneratedMessage. The symbol '_OBJC_CLASS_$_GSDK_PBGeneratedMessage' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed, undefined symbol: _FIRLogError. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(696,3): error : Native linking failed. Please review the build log.
```
