### ISSUE TITLE
Xamarin.Firebase.iOS.CloudMessaging 4.1.1 crashes app at launch

### ISSUE THREAD

**Issue by Xyotic** [xamarin/GoogleApisForiOSComponents#314] opened 2019-10-09 09:21 UTC
Upgrade form Xamarin.Firebase.iOS.CloudMessaging 3.1.2 to Version 4.1.1 crashes my app imediatly at launch.

I get this error:
> Xamarin.Hosting: Process '295' exited.
> Application 'com.myCompany.myApp' terminated.
> dyld: Library not loaded: @rpath/protobuf.framework/protobuf
>   Referenced from: /private/var/containers/Bundle/Application/FAB28A28-F56D-4D03-85C1-9F0B136E9557/myApp.iOS.app/Frameworks/FirebaseMessaging.framework/FirebaseMessaging
>   Reason: image not found

**Comment by SotoiGhost** [comment] 2019-10-11 20:56
This seems to be a duplicate of #311. Closing this now.

**Closed by SotoiGhost** 2019-10-11 20:56 UTC
