### ISSUE TITLE
Firebase Messaging crashing iOS Xamarin App

### ISSUE THREAD

**Issue by Edalzebu** [xamarin/GoogleApisForiOSComponents#313] opened 2019-10-08 22:38 UTC
Hello,

So i added Firebase CloudMessaging to my iOS Xamarin App, I followed this tutorial 

https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/docs/Firebase/CloudMessaging/GettingStarted.md#add-firebase-to-your-app

I added the iOS Firebase Nuget package and its dependencies, also am able to add Firebase.Core.App.Configure(); to the FinishedLaunching callback up to this point my app works just fine. 

Once I assign a class which implements IMessagingDelegate to the shared instance, i get the next error just after showing the splash screen.

`Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib 'rpath protobuf.framework/protobuf' not found for '/private/var/containers/Bundle/Application/79123E84-9651-424A-8424-D152D3AF5F5B/AnApp.app/Frameworks/FirebaseMessaging.framework FirebaseMessaging', tried but didn't find: '/private/var/containers/Bundle/Application/79123E84-9651-424A-8424-D152D3AF5F5B/AnApp.app/Frameworks/protobuf.framework/protobuf' '/private/var/containers/Bundle/Application/79123E84-9651-424A-8424-D152D3AF5F5B/AnApp.app/Frameworks/FirebaseMessaging.framework/Frameworks/protobuf.framework/protobuf' '/private/var/containers/Bundle/Application/79123E84-9651-424A-8424-D152D3AF5F5B/AnApp.app/Frameworks/protobuf.framework/protobuf' 'rpath protobuf.framework/protobuf' '/System/Library/Frameworks/protobuf.framework/protobuf'
Highlighted by Thread: 0`

I have been struggling with this for some time, any help would be greatly appreciated.

**Comment by remeesms** [comment] 2019-10-11 07:01
Any Update, Form me this is showing after update the nuget packages to 

```
<package id="Xamarin.Firebase.iOS.Auth" version="6.2.1" targetFramework="xamarinios10" />
 <package id="Xamarin.Firebase.iOS.CloudMessaging" version="4.1.1" targetFramework="xamarinios10" />
 <package id="Xamarin.Firebase.iOS.Core" version="6.1.0" targetFramework="xamarinios10" />
 <package id="Xamarin.Firebase.iOS.Database" version="6.0.0" targetFramework="xamarinios10" />
 <package id="Xamarin.Firebase.iOS.InstanceID" version="4.2.1" targetFramework="xamarinios10" />
 <package id="Xamarin.Firebase.iOS.Storage" version="3.4.0" targetFramework="xamarinios10" />
```

**Comment by Edalzebu** [comment] 2019-10-11 07:04
Hey @remeesms,

Yeah i downgraded the packages and now its working, seems the new packages has some issues.

Right now am using:

Xamarin.Firebase.iOS.CloudMessaging (3.1.2)
Xamarin.Firebase.iOS.Core (5.1.3)
Xamarin.Firebase.iOS.InstanceID (3.2.1)

And its working fine.

**Comment by remeesms** [comment] 2019-10-11 07:43
@Edalzebu 

Thanks, Do you know what is the Auth version for this?

**Comment by SotoiGhost** [comment] 2019-10-11 20:54
This seems to be a duplicate of #311. Closing this now.

**Closed by SotoiGhost** 2019-10-11 20:54 UTC
