### ISSUE TITLE
Crashes on release mode unless I have debug enabled

### ISSUE THREAD

**Issue by chrisfoulds** [xamarin/GoogleApisForiOSComponents#127] opened 2018-02-05 15:06 UTC
App runs fine in debug on device and simulator.

Switch to release mode and I get
Objective-C exception thrown.  Name: FIRAppNotConfigured Reason: Failed to get default Firebase Database instance. Must call `[FIRApp configure]` (`FirebaseApp.c<\M-b\M^@\M-&>

However if I turn on ‘Enable Debugging’ in iOS Debug options it all works again.

Very puzzled, any tips ?

**Comment by SotoiGhost** [comment] 2018-02-06 19:58
@chrisfoulds I have just tested the sample on Release on a real device and everything worked as expected. Please, make sure that you are calling `App.Configure ()` method before any other Firebase method.

Also, if you can provide a test case would be very helpful.

Best.

**Comment by chrisfoulds** [comment] 2018-02-08 10:24
So I could not recreate on new projects either so I did some more investigation.
Basically by adding a
await Task.Yield();

after these two lines
```
            Firebase.Core.App.Configure();
            Database.DefaultInstance.PersistenceEnabled = true;
```

and before this line :
`DatabaseReference rootNode = Database.DefaultInstance.GetRootReference();`

It works.

**Comment by SotoiGhost** [comment] 2018-02-08 21:41
It seems that the issue is resolved now. I'm closing this. Feel free to reopen it if something else happens related to this.

**Closed by SotoiGhost** 2018-02-08 21:41 UTC
